### ISSUE TITLE
Support Django 4

### ISSUE THREAD

**Issue by mr-flibble** [praekeltfoundation/django-google-analytics#71]
Hello, is possible add support for Django 4? Now its incompatible.
Thanks

> The conflict is caused by:
>     The user requested Django==4.0.2
>     django-celery 3.3.1 depends on django>=1.8
>     django-google-analytics-app 5.0.3 depends on Django<3.3 and >=2.2.5

**Comment by rudigiesler** [comment]
PR to add django 4.0 support: https://github.com/praekeltfoundation/django-google-analytics/pull/72

**Comment by nemecek-filip** [comment]
@rudigiesler awesome! Thank you 👍

**Comment by rudigiesler** [comment]
Hi! So the current PyPI package is owned by our sister company https://pypi.org/user/Praekelt/ . I'm currently trying to get it transferred over to us https://pypi.org/user/praekelt.org/ . Once that is done, I can generate a key and it can be published. Unfortunately I don't have any insight on how long it will take.

The publish action failed because I haven't been able to generate a key to add to the repo secrets. Once I can do that, I'll rerun the publish action.

**Comment by rudigiesler** [comment]
Release 5.0.4 fixes this issue: https://pypi.org/project/django-google-analytics-app/5.0.4/

It also adds support for Celery 5, as there is a CVE in celery 4
